name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log In to Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag unraidr/docker-mediawiki:latest
      
    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_REPO: ${{secrets.DOCKER_REPO}}
      run: |
        docker push unraidr/docker-mediawiki:latest
